services:
  bot:
    user: 1000:1000
    build:
      context: .
      dockerfile: Docker/bot/Dockerfile
    env_file:
      - app/.env.local
    restart: unless-stopped
    volumes:
      - ./app:/bot

